import fs from 'node:fs';
import path from 'node:path';
import { Command } from 'commander';
import ora from 'ora';
import { ConfigStore } from '../core/config-store.js';
import { SshService } from '../core/ssh-service.js';
import { getOctomuxDir, getSshDir } from '../platform/paths.js';
import { promptConfirm } from '../ui/prompts.js';
import { logger } from '../ui/logger.js';

export function registerUninstallCommand(program: Command): void {
  program
    .command('uninstall')
    .alias('purge')
    .description('Safely clean up octomux configurations, SSH blocks, and local data')
    .option('--delete-keys', 'Also delete octomux-generated SSH private & public keys')
    .option('-y, --yes', 'Skip interactive confirmation')
    .action(async (options) => {
      const configStore = new ConfigStore();
      const sshService = new SshService();

      logger.warn('This will safely remove octomux configurations from your system.');

      if (!options.yes) {
        const confirmed = await promptConfirm(
          'Are you sure you want to clean up all octomux managed configurations?',
          false
        );
        if (!confirmed) {
          logger.info('Uninstall operation aborted.');
          return;
        }
      }

      let deleteKeys = Boolean(options.deleteKeys);
      if (!options.yes && !options.deleteKeys) {
        deleteKeys = await promptConfirm(
          'Do you also want to delete all SSH keys generated by octomux (~/.ssh/id_*_octomux_*)?',
          false
        );
      }

      const spinner = ora('Cleaning up octomux configurations...').start();

      try {
        // 1. Clean ~/.ssh/config managed block
        sshService.syncSshConfig([]);
        spinner.text = 'Cleaned octomux managed block in ~/.ssh/config...';

        // 2. Optionally delete generated SSH keys
        if (deleteKeys) {
          const accounts = Object.values(configStore.getAccounts());
          for (const acc of accounts) {
            if (fs.existsSync(acc.ssh.keyPath)) {
              try {
                fs.unlinkSync(acc.ssh.keyPath);
              } catch {
                // Ignore file lock errors
              }
            }
            if (fs.existsSync(acc.ssh.publicKeyPath)) {
              try {
                fs.unlinkSync(acc.ssh.publicKeyPath);
              } catch {
                // Ignore
              }
            }
          }

          // Scan ~/.ssh for any orphaned id_*_octomux_* files
          const sshDir = getSshDir();
          if (fs.existsSync(sshDir)) {
            const files = fs.readdirSync(sshDir);
            for (const file of files) {
              if (file.includes('_octomux_')) {
                try {
                  fs.unlinkSync(path.join(sshDir, file));
                } catch {
                  // Ignore
                }
              }
            }
          }
        }

        // 3. Remove ~/.octomux directory
        const octomuxDir = getOctomuxDir();
        if (fs.existsSync(octomuxDir)) {
          fs.rmSync(octomuxDir, { recursive: true, force: true });
        }

        spinner.succeed('octomux configurations cleaned up successfully!');

        const lines = [
          'octomux data has been safely uninstalled:',
          '  ✔ Cleaned managed entries from ~/.ssh/config (custom user hosts preserved)',
          deleteKeys
            ? '  ✔ Deleted octomux-generated SSH keys'
            : '  ℹ Preserved SSH keys in ~/.ssh/',
          '  ✔ Removed ~/.octomux configuration store',
          '',
          'To remove the npm binary package, run:',
          '  npm uninstall -g octomux   (or "npm unlink -g octomux" for dev builds)',
        ];

        logger.box(lines.join('\n'), 'Safe Uninstall Complete', 'green');
      } catch (err: unknown) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        spinner.fail(`Failed to clean up: ${errorMsg}`);
        process.exit(1);
      }
    });
}
